server:
  port: 8083 #配置服务端口

spring:
#  profiles:
#    active:
  application:
    name: microservice-base #服务名称-服务之间使用名称进行通讯
    # 数据库访问配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka #填写注册中心服务器地址
    register-with-eureka: true  #是否需要将自己注册到注册中心
    fetch-registry: true  #是否需要搜索服务信息
  instance:
    prefer-ip-address: true #使用ip地址注册到注册中心
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #注册中心列表中显示的状态参数


ribbon:
  ReadTimeout: 15000  #建立连接超时时间
  ConnectTimeout: 15000  #读取资源超时间


hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds:  15000