server:
  port: 9527  #配置服务端口

spring:
  application:
    name: AliCloud-gateway-gateway9527 #服务名称-服务之间使用名称进行通讯

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          lower-case-service-id: true   # 允许为小写

      routes:
#        - id: payment_routh1 #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:5001   #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/ok/**   #断言,路径相匹配的进行路由
#        # 上面表示 如果要访问http://localhost:5001/payment/ok/** 需要
#        # http://localhost:9527/payment/ok/**
        - id: ALICLOUD-OPENGIN-CONSUMER-ORDER5002  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://ALICLOUD-OPENGIN-CONSUMER-ORDER5002     #真实调用地址      lb为负载均衡
          predicates:
            - Path=/consumer/**   #断言,路径相匹配的进行路由  (这里不能直接/**，最好加上controller一级名称 否则路由不知道哪个服务controller 否则可能会出现默认多个路由只生效一个)

        - id: ALICLOUD-HYSTRIX-PROVIDER-PAYMENT5001 #路由的ID，没有固定规则但要求唯一，建议配合服务名
            # uri: http://localhost:5001   #匹配后提供服务的路由地址
          uri: lb://ALICLOUD-HYSTRIX-PROVIDER-PAYMENT5001	 # lb 为负载均衡
          predicates:
            - Path=/payment/**   #断言,路径相匹配的进行路由  (这里不能直接/**，最好加上controller一级名称 否则路由不知道哪个服务controller 否则可能会出现多个路由只生效一个)
            #- After=2020-03-08T10:59:34.102+08:00[Asia/Shanghai]
            #- Cookie=username,zhangshuai #并且Cookie是username=zhangshuai才能访问
            #- Header=X-Request-Id, \d+ #请求头中要有X-Request-Id属性并且值为整数的正则表达式
            #- Host=**.atguigu.com
            #- Method=GET
            #- Query=username, \d+ #要有参数名称并且是正整数才能路由

eureka:
  client:
    service-url:
#     defaultZone: http://127.0.0.1:3000/eureka #填写注册中心服务器地址(单机版)
      defaultZone: http://eureka3000.com:3000/eureka,http://eureka3000.com:3000/eureka #填写注册中心服务器地址(集群版)
    register-with-eureka: true  #是否需要将自己注册到注册中心
    fetch-registry: true  #是否需要搜索服务信息
  instance:
    prefer-ip-address: true #使用ip地址注册到注册中心
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #注册中心列表中显示的状态参数








