server:
  port: 5002  #配置服务端口

spring:
  application:
    name: springcloud-opengin-consumer-order5002 #服务名称-服务之间使用名称进行通讯

eureka:
  client:
    service-url:
#     defaultZone: http://127.0.0.1:3000/eureka #填写注册中心服务器地址(单机版)
      defaultZone: http://eureka3000.com:3000/eureka,http://eureka3000.com:3000/eureka #填写注册中心服务器地址(集群版)
    register-with-eureka: true  #是否需要将自己注册到注册中心
    fetch-registry: true  #是否需要搜索服务信息
  instance:
    prefer-ip-address: true #使用ip地址注册到注册中心
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #注册中心列表中显示的状态参数

#负载均衡 ribbon会默认负载均衡  假如同一个服务名字 多个端口部署   会自动分配调用哪个服务  不设置的话默认openFegin超时时间是1s  这个没提示。。。。
ribbon:
  ReadTimeout: 7000  #建立连接超时时间
  ConnectTimeout: 7000  #读取资源超时间


#将feign的接口信息请求打印
logging:
  level:
  #Feign日志以什么级别监控哪个接口 (填写FeignService路径)
    com.cn.service.PaymentFeignService: debug


#打开fegin对hystrix的依赖 否则熔断器不生效
feign:
  hystrix:
    enabled: true






