server:
  port: 9002  #配置服务端口

spring:
  application:
    name: alibabacloud-provider-payment9001 #服务名称-服务之间使用名称进行通讯
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


management:
  endpoints:
    web:
      exposure:
        include: '*'
















