server:
  port: 8401  #配置服务端口

spring:
  application:
    name: alibabacloud-sentinel-service8401 #服务名称-服务之间使用名称进行通讯
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      filter:
        url-patterns: /**
      transport:
        #配置 sentinel dashboard地址
        dashboard: 127.0.0.1:6789
        #默认8719端口，假如被占用会从8719开始 依次+1扫描，知道找到未被占用端口。
        port: 8719
        client-ip: 127.0.0.1



management:
  endpoints:
    web:
      exposure:
        include: '*'

















