server:
  port: 5001  #配置服务端口

spring:
  application:
    name: AliCloud-hystrix-provider-payment5001 #服务名称-服务之间使用名称进行通讯

eureka:
  client:
    service-url:
#     defaultZone: http://127.0.0.1:3000/eureka #填写注册中心服务器地址(单机版)
      defaultZone: http://eureka3000.com:3000/eureka,http://eureka3000.com:3000/eureka #填写注册中心服务器地址(集群版)
    register-with-eureka: true  #是否需要将自己注册到注册中心
    fetch-registry: true  #是否需要搜索服务信息
  instance:
    prefer-ip-address: true #使用ip地址注册到注册中心
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #注册中心列表中显示的状态参数













