server:
  port: 9801  #配置服务端口

spring:
  application:
    name: alibabacloud-consumer-order9801 #服务名称-服务之间使用名称进行通讯
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


#消费者将要去访问的微服务名称(这里是自己配的，只是为了后面方便作为参数使用)
service-url:
  nacos-user-service: http://alibabacloud-provider-payment9001
















