server:
  port: 3000  #配置服务端口

spring:
  application:
    name: AliCloud-eureka-server3000  #服务名称 - 服务之间使用名称进行通讯


eureka:
  instance:
    hostname:  127.0.0.1  #eureka服务端实例名称
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka #填写注册中心服务器地址
    register-with-eureka: false  #是否需要将自己注册到注册中心
    fetch-registry: false  #是否需要搜索服务信息






