server:
  port: 2001  #配置服务端口

spring:
  application:
    name: alibabacloud-seata-order-service2001 #服务名称-服务之间使用名称进行通讯
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos配置
    alibaba:
      seata:
        tx-service-group: cn_group  #seata配置(自定义事务组名称需要与seata-server中的对应)
  #数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata-order?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: 123456

feign:
  hystrix:
    enabled: false #关闭熔断，测试分布式事务



logging:
  level:
    io:
      seata: info

management:
  endpoints:
    web:
      exposure:
        include: '*'


mybatis-plus:
  #指明mapper.xml扫描位置(classpath* 代表编译后类文件根目录)
  #    #主键类型 0:数据库ID自增, 1:用户输入ID,2:全局唯一ID (数字类型唯一ID), 3:全局唯一ID UUID
  global-config.id-type: 0
  global-config:
    #字段策略(拼接sql时用于判断属性值是否拼接) 0:忽略判断,1:非NULL判断,2:非空判断
    # field-strategy: 2
    #驼峰下划线转换含查询column及返回column(column下划线命名create_time，返回java实体是驼峰命名createTime，开启后自动转换否则保留原样)
    db-column-underline: true
    #    #是否动态刷新mapper
    refresh-mapper: false
    #数据库大写命名下划线转换
    #capital-mode: true
  configuration:
    #打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**Mapper.xml












